require "exception_notification/rails"

if Rails.env.production?
  app_name = "WorkFlow"
  recipients = %w[bug@amastek.com]
else
  app_name = "WorkFlow(QC) "
  recipients = %w[debug@amastek.com]
end

ExceptionNotification.configure do |config|
  # Ignore additional exception types.
  # ActiveRecord::RecordNotFound, Mongoid::Errors::DocumentNotFound,
  # AbstractController::ActionNotFound and ActionController::RoutingError are already added.
  # config.ignored_exceptions += %w{ActionView::TemplateError CustomError}

  # Adds a condition to decide when an exception must be ignored or not.
  # The ignore_if method can be invoked multiple times to add extra conditions.
  config.ignore_if do |_exception, _options|
    !(Rails.env.production? || Rails.env.staging?)
  end

  # Ignore exceptions generated by crawlers
  # config.ignore_crawlers %w{Googlebot bingbot}

  # Notifiers =================================================================

  # Email notifier sends notifications by email.
  config.add_notifier :email, {
    email_prefix: "[#{app_name}]",
    sender_address: %("Notifier" <notifier@mg.amastek.com>),
    exception_recipients: recipients,
    error_grouping: true,
    error_grouping_period: 5.minutes,
    error_grouping_cache: Rails.cache,
  }

  config.add_notifier :slack, {
    webhook_url: "https://hooks.slack.com/services/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",
    channel: "#alert-pms",
    username: app_name,
    additional_parameters: {
      icon_emoji: ":bug:",
      mrkdwn: true,
    },
  }
end
